### PR TITLE
WPEBACKEND-RDK Support WPE MiniBrowser and Cog

### PR DESCRIPTION
**Pull request by munezbn**
Added support to run wpewebkit with wpebackend-rdk.
Added a new defconfig for raspberri-pi3 to build wpewebkit with wpebackend-rdk and rpi-userland
Added patch to MiniBrowser to make it configurable with wpebackends ( FDO or RDK)
Modified wpewebkit build package files to make it compatible with old and new gstreamer

NOTE : Tested on RPI3 (USERLAND/DISPMANX) and able to launch MiniBrowser and Cog. But YT is not playing.

### CODE REVIEW

**Comment by munezbn** [comment]
Hi @aperezdc @mcatanzaro 
Can you please have a look at this.

File: package/libwpe/libwpe.mk [hunk 1]
```diff
@@ -10,5 +10,8 @@ LIBWPE_SOURCE = libwpe-$(LIBWPE_VERSION).tar.xz
 LIBWPE_LICENSE = BSD-2-Clause
 LIBWPE_INSTALL_STAGING = YES
 LIBWPE_DEPENDENCIES = libegl libxkbcommon
+LIBWPE_CONF_OPTS += \
+    -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) -D_GNU_SOURCE" \
+    -DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) -D_GNU_SOURCE"
```
Comment (aperezdc) [inline package/libwpe/libwpe.mk]: I'm not a fan of passing `CMAKE_{C,CXX}_FLAGS` in build recipes, because if the CMake files overwrites them, the values added can be silently lost; and also Buildroot passes `TARGET_{C,CXX}FLAGS` using a toolchain CMake module file.

The correct way to handle such options is to detect in the project CMake files whether the flag is needed. If you really need to add compiler flags, CMake should take into account the `{C,CXX}FLAGS` environment variables, so I would rather have them added in the environment variables using `LIBWPE_CONF_ENV`.

Last but not least... Is `-D_GNU_SOURCE` really needed? I don't remember needing it when building the RDK backend myself :thinking:

File: package/wpebackend-rdk/Config.in [hunk 2]
```diff
@@ -0,0 +1,8 @@
+config BR2_PACKAGE_WPEBACKEND_RDK
+    bool "wpebackend-rdk"
+    select BR2_PACKAGE_WAYLAND_EGL_BNXS if BR2_PACKAGE_HAS_NEXUS && BR2_PACKAGE_WESTEROS
+    select BR2_PACKAGE_LIBWPE
+    select BR2_PACKAGE_XKEYBOARD_CONFIG
+    select BR2_PACKAGE_LIBINPUT if !BR2_PACKAGE_WPEFRAMEWORK_COMPOSITOR
+    help
+      RDK-specific implementations of the WPEBackend interfaces.
```
Comment (aperezdc) [inline package/wpebackend-rdk/Config.in]: Small nit: The help text could be a bit more descriptive and indicate which hardware is supported by it.

File: package/wpebackend-rdk/Config.in [hunk 3]
```diff
@@ -0,0 +1,8 @@
+config BR2_PACKAGE_WPEBACKEND_RDK
+    bool "wpebackend-rdk"
+    select BR2_PACKAGE_WAYLAND_EGL_BNXS if BR2_PACKAGE_HAS_NEXUS && BR2_PACKAGE_WESTEROS
```
Comment (aperezdc) [inline package/wpebackend-rdk/Config.in]: None of this symbols is present in upstream Buildroot, nor in the WPE overlay. Please remove this line that refers to them.

File: package/wpebackend-rdk/Config.in [hunk 4]
```diff
@@ -0,0 +1,8 @@
...
+    select BR2_PACKAGE_LIBWPE
+    select BR2_PACKAGE_XKEYBOARD_CONFIG
+    select BR2_PACKAGE_LIBINPUT if !BR2_PACKAGE_WPEFRAMEWORK_COMPOSITOR
```
Comment (aperezdc) [inline package/wpebackend-rdk/Config.in]: There is no `BR2_PACKAGE_WPEFRAMEWORK_COMPOSITOR` in upstream Buildroot, neither in the WPE overlay. Please remove.

File: package/wpebackend-rdk/wpebackend-rdk.mk [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+
+WPEBACKEND_RDK_VERSION = 0b628970fbcdd0346557db630fc07e909f9dd38b 
+WPEBACKEND_RDK_SITE = $(call github,WebPlatformForEmbedded,WPEBackend-rdk,$(WPEBACKEND_RDK_VERSION))
+WPEBACKEND_RDK_INSTALL_STAGING = YES
+WPEBACKEND_RDK_DEPENDENCIES = libwpe libglib2
+
+WPEBACKEND_RDK_FLAGS = 
+
+ifeq ($(BR2_PACKAGE_LIBXKBCOMMON),y)
+WPEBACKEND_RDK_DEPENDENCIES += xkeyboard-config
```
Comment (aperezdc) [inline package/wpebackend-rdk/wpebackend-rdk.mk:13]: If the line is correct, then in `Config.in` the package should probably select `BR2_PACKAGE_XKEYBOARD_CONFIG`. I don't understand why `xkeyboard-config` is needed here, and I think this is meant to be `libxkbcommon`.

File: package/wpebackend-rdk/wpebackend-rdk.mk [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+WPEBACKEND_RDK_FLAGS += -DUSE_BACKEND_INTEL_CE=ON
+
+else ifeq ($(BR2_PACKAGE_VIP_SDK)$(BR2_PACKAGE_UMA_SDK),y)
+    WPEBACKEND_RDK_FLAGS += -DUSE_BACKEND_BCM_NEXUS=ON
+endif
+
+ifeq ($(BR2_PACKAGE_VSS_SDK),y)
+    WPEBACKEND_RDK_FLAGS += -DNEXUS_CLIENT_MODE=ON \
+                            -DUSE_BACKEND_BCM_NEXUS=ON
+endif
```
Comment (aperezdc) [inline package/wpebackend-rdk/wpebackend-rdk.mk:20]: Again, there's a bunch of stuff here which is not present in upstream Buildroot, nor in the WPE overlay. Please make this use only defined symbols, and make sure that the needed flags to build a working version of the backend which uses packages and features available in upstream Buildroot.

File: package/wpebackend-rdk/wpebackend-rdk.mk [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+
+WPEBACKEND_RDK_CONF_OPTS = \
```
Comment (aperezdc) [inline package/wpebackend-rdk/wpebackend-rdk.mk]: Instead of using an auxiliary `WPEBACKEND_RDK_FLAGS` variable, please append build configuration options directly to `WPEBACKEND_RDK_CONF_OPTS`.

File: package/wpewebkit/Config.in [hunk 8]
```diff
@@ -55,6 +54,29 @@ config BR2_PACKAGE_WPEWEBKIT
 
 if BR2_PACKAGE_WPEWEBKIT
 
+choice
```
Comment (aperezdc) [inline package/wpewebkit/Config.in:68]: Instead of a `choice` section which only allows choosing a single backend, I would like to make it possible to build multiple backends. While in general I don't expect that to be used often, there are a few use cases, and it's handy for development/testing.

File: package/wpewebkit/Config.in [hunk 9]
```diff
@@ -55,6 +54,29 @@ config BR2_PACKAGE_WPEWEBKIT
...
+config BR2_PACKAGE_WPEWEBKIT_BACKEND_RDK
+	bool "RDK Backend"
+	select BR2_PACKAGE_WPEBACKEND_RDK
+	help
+	  Use WPEBACKEND_RDK as the backend.
+
+endchoice
+
+config BR2_PACKAGE_WPEWEBKIT_LAUNCHER_MINIBROWSER
+	bool "MiniBrowser"
```
Comment (aperezdc) [inline package/wpewebkit/Config.in]: This should have a `depends on BR2_PACKAGE_WPEBACKEND_FDO || BR2_PACKAGE_WPEBACKEND_RDK` line.

File: package/wpewebkit/Config.in [hunk 10]
```diff
@@ -76,8 +98,13 @@ config BR2_PACKAGE_WPEWEBKIT_MULTIMEDIA
 	bool "multimedia support"
 	select BR2_PACKAGE_GSTREAMER1
 	select BR2_PACKAGE_GST1_PLUGINS_BAD
+	select BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_GL if BR2_PACKAGE_HAS_LIBEGL || BR2_PACKAGE_HAS_LIBGL
 	select BR2_PACKAGE_GST1_PLUGINS_BAD_PLUGIN_MPEGTSDEMUX
+	select BR2_PACKAGE_GST1_PLUGINS_BAD_LIB_OPENGL if BR2_PACKAGE_HAS_LIBEGL || BR2_PACKAGE_HAS_LIBGL
+	select BR2_PACKAGE_GST1_PLUGINS_BAD_HAS_LIB_OPENGL if BR2_PACKAGE_GST1_PLUGINS_BAD_LIB_OPENGL
```
Comment (aperezdc) [inline package/wpewebkit/Config.in]: The `BR2_PACKAGE_GST1_PLUGINS_BAD_HAS_LIB_OPENGL` should be selected by the GStreamer build recipes automatically when `BR2_PACKAGE_GST1_PLUGINS_BAD_LIB_OPENGL` is enabled; please do not set it here.

File: package/wpewebkit/Config.in [hunk 11]
```diff
@@ -76,8 +98,13 @@ config BR2_PACKAGE_WPEWEBKIT_MULTIMEDIA
...
 	select BR2_PACKAGE_GST1_PLUGINS_BASE
+	select BR2_PACKAGE_GST1_PLUGINS_BASE_LIB_OPENGL if BR2_PACKAGE_HAS_LIBGL || BR2_PACKAGE_HAS_LIBGLES
+	select BR2_PACKAGE_GST1_PLUGINS_BASE_HAS_LIB_OPENGL if BR2_PACKAGE_GST1_PLUGINS_BASE_LIB_OPENGL
```
Comment (aperezdc) [inline package/wpewebkit/Config.in]: Ditto.

File: package/wpewebkit/wpewebkit.mk [hunk 12]
```diff
@@ -64,6 +78,42 @@ else
...
+endif
+
+ifeq ($(BR2_PACKAGE_WOFF2),y)
+WPEWEBKIT_CONF_OPTS += -DUSE_WOFF2=ON
+WPEWEBKIT_DEPENDENCIES += woff2
+else
+WPEWEBKIT_CONF_OPTS += -DUSE_WOFF2=OFF
+endif
+
+ifeq ($(BR2_PACKAGE_NINJA),y)
```
Comment (aperezdc) [inline package/wpewebkit/wpewebkit.mk]: I am not a fan of this. The upstream Buildroot policy is to let CMake use whichever build tool it wants to use by default. None of the upstream packages do anything like this, and I would rather trust what `$(eval $(cmake-package))` does instead of overriding the build and install commands.

File: package/wpewebkit/wpewebkit.mk [hunk 13]
```diff
@@ -64,6 +78,42 @@ else
...
+WPEWEBKIT_CONF_OPTS += -G Ninja
+WPEWEBKIT_DEPENDENCIES += host-ninja
+WPEWEBKIT_MAKE = $(HOST_DIR)/usr/bin/ninja
+endif
+
+define WPEWEBKIT_INSTALL_STAGING_CMDS
+    install -Dm755 $(@D)/bin/WPE{Network,Storage,Web}Process $(STAGING_DIR)/usr/bin/ && \
```
Comment (aperezdc) [inline package/wpewebkit/wpewebkit.mk]: Also: do not install manually all this stuff. You should be using a single command here:

```sh
DESTDIR=$(STAGING_DIR) $(HOST_DIR)/usr/bin/cmake \
    -DCOMPONENT=Development --build $(@D) --target=install
```

But as I said: please remove the unneeded overrides to use Ninja.

File: patches/wpewebkit/0001-add-wpebackednd-configuration-support.patch [hunk 14]
```diff
@@ -0,0 +1,125 @@
...
+ 
++#if defined(USE_WPEBACKEND_FDO) && USE_WPEBACKEND_FDO
+     auto backend = createViewBackend(1280, 720);
+     struct wpe_view_backend* wpeBackend = backend->backend();
+     if (!wpeBackend) {
+@@ -134,6 +141,10 @@
+     auto* viewBackend = webkit_web_view_backend_new(wpeBackend, [](gpointer data) {
+         delete static_cast<WPEToolingBackends::ViewBackend*>(data);
+     }, backend.release());
++#else /* RDK backend*/
```
Comment (aperezdc) [inline patches/wpewebkit/0001-add-wpebackednd-configuration-support.patch]: This is not really specific to the RDK backend, and would work for any backend that is installed as `libWPEBackend-default.so`.

File: patches/wpewebkit/0002-Define-MESA_EGL_NO_X11_HEADERS-when-not-using-GLX.patch [hunk 15]
```diff
@@ -0,0 +1,13 @@
+--- a/Tools/wpe/backends/ViewBackend.cpp	2018-10-04 10:04:52.264448058 +0000
++++ b/Tools/wpe/backends/ViewBackend.cpp	2018-10-04 10:06:02.232680294 +0000
+@@ -25,6 +25,10 @@
+ 
+ #include "ViewBackend.h"
+ 
++#if !defined(USE_GLX) || !USE_GLX
++// This define is used in mesa and other GL implementations to exlcude X11 headers.
++#define MESA_EGL_NO_X11_HEADERS 1
```
Comment (aperezdc) [inline patches/wpewebkit/0002-Define-MESA_EGL_NO_X11_HEADERS-when-not-using-GLX.patch]: This should not be needed. I have fixed similar related to X11 definitions being used by the EGL headers, and the tempting path of defining `MESA_EGL_NO_X11_HEADERS` is wrong 99.99% of the time. An EGL implementation is responsible to provide headers which are usable without defining this, and if they need it (like Mesa's headers, which are generic) then they must ship an `egl.pc` file which contains the needed compiler flags, or have whichever definition the implementation needs elsewhere (for example including `waylang-egl.h` defines `WL_EGL_PLATFORM`, which is later used by `eglplatform.h`). It is never the responsibility of code that uses EGL to have to manually define a low-level switcheroo like this.

**Review by aperezdc — CHANGES_REQUESTED** [review]
I would love to have this PR applied to the repository, but I would like to request a number of changes before merging it. The final goal of this overlay is to have a working set of recipes that can be sent to upstream Buildroot, and therefore the build recipes should follow upstream conventions as much as possible. Please take a look at the review comments, I am sure we can get this PR into shape :clap: 

P.S: The Buildroot source tree includes an `utils/check-package` script which can be used to lint the build recipes — it also gives good hints, so please use it at ease when editing files :wink:

**Comment by munezbn** [comment]
@aperezdc  thanks for all the reviews i will work on the changes and get back to you again :).
please note that RDK  buildroot package changes I took from the old buildroot-wpe which I had them locally in my PC :). By the way do we really need Gstreamer 1.14. x  for MSE ? I was able to try it 1.12.x and I didn't face any compilation issue. ( I forced WPE  to ignore 1.14 version dependency ). Currently the longterm buildroot release is still using Gstreamer 1.12.x

File: package/libwpe/libwpe.mk (hunk 1 above)
Comment (munezbn) [reply package/libwpe/libwpe.mk]: Compilation was failing without this. The error was related to some CLOCK macro and to fix that error this compiler flag was required

File: package/wpebackend-rdk/Config.in (hunk 3 above)
Comment (munezbn) [reply package/wpebackend-rdk/Config.in]: I used theses files from old wpe-buildroot branch as is. I will consider your comments and cleanu accordingly.

File: package/wpebackend-rdk/wpebackend-rdk.mk (hunk 5 above)
Comment (munezbn) [reply package/wpebackend-rdk/wpebackend-rdk.mk:13]: same comment as above

File: package/wpebackend-rdk/Config.in (hunk 4 above)
Comment (munezbn) [reply package/wpebackend-rdk/Config.in]: same comment as above

File: package/wpebackend-rdk/wpebackend-rdk.mk (hunk 6 above)
Comment (munezbn) [reply package/wpebackend-rdk/wpebackend-rdk.mk:20]: same comment as above

File: package/wpebackend-rdk/wpebackend-rdk.mk (hunk 7 above)
Comment (munezbn) [reply package/wpebackend-rdk/wpebackend-rdk.mk]: same comment as above

File: package/wpewebkit/Config.in (hunk 8 above)
Comment (munezbn) [reply package/wpewebkit/Config.in:68]: Sorry, this choice was mainly for Mini Browser. May be we should name them something like BR2_PACKAGE_MINIBROWSER_BACKEND_FDO/RDK  ..  ? Minibrowser can be enabled only with one backend at a time right.

File: package/wpewebkit/Config.in (hunk 9 above)
Comment (munezbn) [reply package/wpewebkit/Config.in]: Sure will modify

File: package/wpewebkit/Config.in (hunk 10 above)
Comment (munezbn) [reply package/wpewebkit/Config.in]: Agree, But when I tried with latest gstreamer 1.14.x  this flag was not enabled by default hence I did this change as MSE requires Gstreamer 1.14.x . This was not required with Gstreamer 1.12.x. 
Looks like we need to fix Gstreamer config.in . I will recheck-once again

File: package/wpewebkit/Config.in (hunk 11 above)
Comment (munezbn) [reply package/wpewebkit/Config.in]: Ditto :)

File: package/wpewebkit/wpewebkit.mk (hunk 12 above)
Comment (munezbn) [reply package/wpewebkit/wpewebkit.mk]: Ok I will clean it up.

File: package/wpewebkit/wpewebkit.mk (hunk 13 above)
Comment (munezbn) [reply package/wpewebkit/wpewebkit.mk]: Sure. But are you ok with INSTALL_TARGET_CMDS ?

File: patches/wpewebkit/0001-add-wpebackednd-configuration-support.patch (hunk 14 above)
Comment (munezbn) [reply patches/wpewebkit/0001-add-wpebackednd-configuration-support.patch]: I will remove the RDK comments.

File: patches/wpewebkit/0002-Define-MESA_EGL_NO_X11_HEADERS-when-not-using-GLX.patch (hunk 15 above)
Comment (munezbn) [reply patches/wpewebkit/0002-Define-MESA_EGL_NO_X11_HEADERS-when-not-using-GLX.patch]: I think i added this by mistake because I am not using MESA, I am using RPI_USERLAND. But in between I had tried MESA and may be that time I added this Patch. I will clean it up.

File: package/libwpe/libwpe.mk (hunk 1 above)
Comment (aperezdc) [reply package/libwpe/libwpe.mk]: I suppose `CLOCK_MONOTONIC` or similar... which is amusing, because `libwpe` does not use the macro (neither do the FDO or RDK backends). I would really prefer to make the CMake files detect whether the flag is needed, and for that we need to know what was the compilation error. Could you try doing a build with this removed and sharing the error? Thanks in advance!

File: package/wpebackend-rdk/Config.in (hunk 3 above)
Comment (aperezdc) [reply package/wpebackend-rdk/Config.in]: Thanks! Looking forward for your update with the cleanups :slightly_smiling_face:

File: package/wpewebkit/wpewebkit.mk (hunk 13 above)
Comment (aperezdc) [reply package/wpewebkit/wpewebkit.mk]: Ah, I should have been clearer: None of the `WPEWEBKIT_*_CMDS` should be needed. You can use the [upstream webkitgtk.mk file](https://git.buildroot.net/buildroot/tree/package/webkitgtk/webkitgtk.mk) for inspiration :wink:

**Comment by aperezdc** [comment]
@munezbn Regarding the MSE support, it is strongly recommended to use 1.14.4 — if updating is on the table for you.

It may be possible to make it work with GStreamer 1.12.x but you will need to patch GStreamer. At least you will need to bring back some patches removed in [r236960](https://trac.webkit.org/changeset/236960) and maybe some from [r232060](https://trac.webkit.org/changeset/232060), which we used to have in the WebKit JHBuild environment and now are merged in the latest 1.14.x release. You can run `git log Tools/gstreamer/jhbuild.modules` in a clone of the WebKit repository to find out more. Note that I am not very familiar with the MSE code, so I cannot give you a guarantee that everything will work well with a patched GStreamer 1.12.x

I hope the tips above help. At any rate, thanks again for your time :slightly_smiling_face:

File: package/libwpe/libwpe.mk (hunk 1 above)
Comment (munezbn) [reply package/libwpe/libwpe.mk]: The error is below. I have not used _CONF_ENV variables. How to actually define -D_GNU_SOURCE using it ?

../../host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/interface/vcos/pthreads/vcos_platform.h: In function ‘vcos_semaphore_wait_timeout’:
../../host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/interface/vcos/pthreads/vcos_platform.h:297:22: error: ‘CLOCK_REALTIME’ undeclared (first use in this function)
    if (clock_gettime(CLOCK_REALTIME, &ts) == -1)

File: package/wpebackend-rdk/Config.in (hunk 4 above)
Comment (munezbn) [reply package/wpebackend-rdk/Config.in]: @aperezdc  we still need to select BR2_PACKAGE_LIBINPUT for RDK , ou suggest it to be here in the Config.in ( without depending on WPE_FRAMEWORK) or should I add it into defconfig file ?
Edit : Nevermind, It is used nly by RPI-USERLAND backend so I am adding Config.in
select BR2_PACKAGE_LIBINPUT if BR2_PACKAGE_RPI_USERLAND

File: package/wpebackend-rdk/Config.in (hunk 2 above)
Comment (munezbn) [reply package/wpebackend-rdk/Config.in]: Any suggestion here ? :)  Regarding hardware, I upstream buildroot we can support only BCM Raspberry PI platforms with RPI-USERLAND ..

**Comment by munezbn** [comment]
@aperezdc   Regarding cleanup of wpebackend-rdk,
I found that wpebackend-rd supports multiple backends but with upstream buildroot we can only support Raspberry Pi with rpi-userland. So for now I will only add Raspberry Pi support.

File: package/wpewebkit/wpewebkit.mk (hunk 13 above)
Comment (munezbn) [reply package/wpewebkit/wpewebkit.mk]: I would like to have more discussion on this.

1.  If we dont use WPEWEBKIT_*_CMDS then buildroot will use default rule to install. And The default rule uses Development component which will install development files ( header files, pc files etc) which is fine for STAGING install but not for TARGET install
2.  If we use single command like you mentioned above, it will only install development files ( header files, pc files etc) and wont install library binaries and libraries.

That is why I had added custom commands. Not sure how it works in upstream webkitgtk.mk. Kindly suggest..

File: package/libwpe/libwpe.mk (hunk 1 above)
Comment (aperezdc) [reply package/libwpe/libwpe.mk]: Ouch, this is a bit unfortunate... the package for the Raspberry Pi userland drivers should be the ones defining `_POSIX_C_SOURCE` (or `_GNU_SOURCE`) and putting it into one of its `.pc` files. Or even better: their headers should avoid using functions inside them that need any of this preprocessor symbol being defined. There is already an issue reported related to this, I commented there: https://github.com/raspberrypi/userland/issues/316 :upside_down_face: 

I think we need to keep the hack for now, at least until the issue is solved upstream. To use `_CONF_ENV` you can do something like the following:

```make
# Workaround for https://github.com/raspberrypi/userland/issues/316
ifeq ($(BR2_PACKAGE_RPI_USERLAND),y)
LIBWPE_CONF_ENV += CFLAGS='-D_GNU_SOURCE' CXXFLAGS='-D_GNU_SOURCE'
endif
```

Note how we can use a conditional to add the macro definition only when the Raspberry Pi userland drivers are being used.

File: package/wpebackend-rdk/Config.in (hunk 2 above)
Comment (aperezdc) [reply package/wpebackend-rdk/Config.in]: I would write something like the following in the help text:

> The RDK backend supports a number of different hardware devices. Currently  the Raspberry Pi is the only one supported (using rpi-userland) without using proprietary blobs.

File: package/wpebackend-rdk/Config.in (hunk 4 above)
Comment (aperezdc) [reply package/wpebackend-rdk/Config.in]: Please leave it as `select BR2_PACKAGE_LIBINPUT` — that is: remove the `if !BR2_PACKAGE_WPEFRAMEWORK_COMPOSITOR` part of the line.

File: package/wpebackend-rdk/wpebackend-rdk.mk (hunk 5 above)
Comment (aperezdc) [reply package/wpebackend-rdk/wpebackend-rdk.mk:13]: I double-checked things a bit: the `xkeyboard-config` is the package that installs the XKB data files which describe the different keyboard layout and options. Probably the intention here is to make sure that they are installed, so let's leave it like that for now — you don't need to change anything here (sorry for my misleading comment from earlier).

File: package/wpewebkit/wpewebkit.mk (hunk 13 above)
Comment (aperezdc) [reply package/wpewebkit/wpewebkit.mk]: It's not a problem to use the default commands because Buildroot nowadays automatically cleans up uneeded development files from `$(TARGET_DIR)` at the end of a successful build, using the `target-finalize` Make target, before creating the images — that's why the `webkitgtk.mk` included upstream works fine.

**Comment by aperezdc** [comment]
@munezbn I have added some comments trying to clarify things a bit better. Let me know if you have any other doubts. Thanks again for your effort with this PR :muscle:

File: patches/wpewebkit/0002-Define-MESA_EGL_NO_X11_HEADERS-when-not-using-GLX.patch (hunk 15 above)
Comment (munezbn) [reply patches/wpewebkit/0002-Define-MESA_EGL_NO_X11_HEADERS-when-not-using-GLX.patch]: @aperezdc  Have you tried enabling MiniBrowser in current buildroot overlay ? While trying to build MiniBrowser with FDO backend I got X11 header error.

Like you suggested adding #include <wayland-egl.h> before #include <epoxy/egl.h> will fix the error. Same thing is done in file Tools/wpe/backends/WindowViewBackend.cpp but not in Tools/wpe/backends/ViewBackend.cpp .. Shall I update this patch to include waylang-egl.h

Comment (aperezdc) [reply patches/wpewebkit/0002-Define-MESA_EGL_NO_X11_HEADERS-when-not-using-GLX.patch]: Lately I have been only doing builds with the FDO backend and Mesa's vc4 driver (MiniBrowser builds), but you are right and with the userland driver it doesn't. Adding `#include <wayland-egl.h>` is a good idea :+1:

File: package/libwpe/libwpe.mk (hunk 1 above)
Comment (munezbn) [reply package/libwpe/libwpe.mk]: CONF_ENV approach didn't solve the compilation error. I could see both  CFLAGS and CXXFLAGS set before make command but I still got same error.. So I used old workaround.
Let me know if this is ok  

```
# Workaround for https://github.com/raspberrypi/userland/issues/316
ifeq ($(BR2_PACKAGE_RPI_USERLAND),y)
LIBWPE_CONF_OPTS += -DCMAKE_C_FLAGS='$(TARGET_CFLAGS) -D_GNU_SOURCE' \
                    -DCMAKE_CXX_FLAGS='$(TARGET_CFLAGS) -D_GNU_SOURCE'
endif
```

Comment (aperezdc) [reply package/libwpe/libwpe.mk]: I don't want to make you spend more time with this, so let's use the approach you suggest. It's a workaround, so hopefully we can remove it when the userland libraries fix the root cause.

**Comment by munezbn** [comment]
Hi @aperezdc  
I have addressed almost all the comments. Kindly review the changes and let me know if you want to change anything.  I have also lint the build recipes using check-package tool.

**Review by aperezdc — APPROVED** [review]
@munezbn This is looking very good now. Let's have it merged. Thanks a lot for taking care of all the improvements from the code review :muscle:

**Comment by munezbn** [comment]
Thanks for the merge @aperezdc  looking forward to contribute more in future.
